# PASCAL VOC dataset http://host.robots.ox.ac.uk/pascal/VOC/
# Train command: python train.py --data voc.yaml
# Default dataset location is next to /yolov5:
#   /parent_folder
#     /VOC
#     /yolov5


# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
#train: /mnt/Gu/trainData/Detect/plate_detect/train_detect
#val: /mnt/Gu/trainData/Detect/plate_detect/val_detect
#val: /ssd_1t/derron/yolov5-face/data/widerface/train/  # 4952 images
#train: /cv/all_training_data/plate/cn/yolov7_plate/detect_plate_datasets/train_data
#val: /cv/all_training_data/plate/cn/yolov7_plate/detect_plate_datasets/val_detect

#train: /cv/all_training_data/plate/cn/yolov7_plate/dataset/dataset/train
#val: /cv/all_training_data/plate/cn/yolov7_plate/dataset/dataset/val

# img directory lst: more dataset
train: ["/cv/all_training_data/control/adani/dataset/train",
        "/cv/all_training_data/control/crane/dataset/train",
        "/cv/all_training_data/control/yard/dataset/train",
        "/cv/all_training_data/control/nansha1/dataset/train"
        ]
val: ["/cv/all_training_data/control/adani/dataset/val",
      "/cv/all_training_data/control/crane/dataset/val",
      "/cv/all_training_data/control/yard/dataset/val",
      "/cv/all_training_data/control/nansha1/dataset/val"
     ]
test: ["/cv/all_training_data/control/adani/dataset/test",
       "/cv/all_training_data/control/crane/dataset/test",
       "/cv/all_training_data/control/yard/dataset/test",
       "/cv/all_training_data/control/nansha1/dataset/test"
      ]

# number of classes
nc: 5

# class names
names: ['lorry', 'truckfront', 'truckback', 'container', 'tray']
